#Required packages for LTIB

sudo apt-get install gettext
sudo apt-get install libgtk2.0-dev
sudo apt-get install rpm
sudo apt-get install bison
sudo apt-get install libfreetype6-dev
sudo apt-get install libdbus-glib-1-dev
sudo apt-get install liborbit2-dev
sudo apt-get install intltool
sudo apt-get install ccache
sudo apt-get install ncurses-dev
sudo apt-get install zlib1g
sudo apt-get install zlib1g-dev
sudo apt-get install gcc
sudo apt-get install g++
sudo apt-get install libtool
sudo apt-get install uuid-dev
sudo apt-get install liblzo2-dev
sudo apt-get install tcl
sudo apt-get install dpkg
sudo apt-get install perl
sudo apt-get install binutils
sudo apt-get install libstdc++6
sudo apt-get install libstdc++6-4.6-dev
sudo apt-get install zlibc
sudo apt-get install texinfo
sudo apt-get install autoconf
